baseurl = "/"
languageCode = "en"
title = "Brad Carruthers"
theme = "hugo-theme-cactus-plus"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
    name = "Brad Carruthers"
    job = "Competitive Capitalism & Computational Social Science"
    description = "Passionate about spreading knowledge and solving challenges in developing countries."

    github = "bcallumcarr"

    title404 = "Hmmmm. Looks like you're lost. Maybe head back to the home page? :/"

    aboutAuthor = "Computational Social Scientist"
    iconFont = "font-awesome"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[social]
    github-square = "https://github.com/bcallumcarr"
