---
title: "Research"
author: Brad Carruthers
output: html_document
---

Here is some of the research I am currently working on.

### MSc Thesis LSE: Nudging Online Users Into Asking Better Questions

So after bouncing around quite a bit, I've settled on a topic for my thesis at LSE. I thought it would be cool if there was a way to help users identify whether their questions online have a high or low chance of being answered in a constructive way. The various <a href="https://stackexchange.com/sites#questions" target="_blank">StackExchange</a> fora provide a neat set of large datasets (see <a href="https://archive.org/download/stackexchange" target="_blank">here</a> for the data dump) to play with, and given data on historial questions and answers like the StackExchane datasets, it doesn't appear too hard to predict some kind of "quality" inherent in questions, as shown by <a href="https://www.aaai.org/ocs/index.php/ICWSM/ICWSM14/paper/viewFile/8080/8143" target="_blank">Ravi *et al.* (2014)</a>.

Ravi *et al.* (2014) basically use only the text of StackOverflow questions to predict question scores within the StackOverflow community. Their fancy, suped up model (which is classification regression on Latent Dirichlet Allocation-steroids) manages 72% classification accuracy, beating the 60% accuracy if only page views are used.

Since my aim is to inform users of whether their question will illicit a productive response from a community, I am considering other response variables like the number of edits a question experiences and the sentiment of comments/answers. And speaking of productive responses to clearer questions, you might want to have a look at the <a href="https://bradcarruthers.netlify.com/2019/03/08/annoying-the-stackoverflow-community-for-research/" target="_blank">first ever question I asked on StackExchange</a>, for research purposes of course...





---

### MSc Thesis Research Proposal at LSE: Automatic construction of student misconception ontology from online forum data

Have a look <a href="/img/my400-assignment-after-feedback.pdf" target="_blank">here</a> for a research proposal I put together for an MY400 Social Science Research Design course at LSE. Please note that it is a bit rough after having incorporated some feedback from <a href="https://nickhoernle.com" target="_blank">Nick Hoernle</a> - who also incidentally started me out on this specific topic.

---

### Honours Thesis at Stellenbosch: Teacher job satisfaction and learner performance: An investigation into the 2004 Grade 6 Intermediate Phase Systemic Evaluation

<a href="/img/honours-thesis.pdf" target="_blank">This</a> is my thesis for my Honours in Economics at Stellenbosch University, South Africa.