name = "Cactus Plus"
license = "MIT"
licenselink = "https://github.com/nodejh/hugo-theme-cactus-plus/blob/master/LICENSE.md"
description = "A minimalistic and responsive theme for bloggers."
homepage = "https://github.com/nodejh/hugo-theme-simple"
tags = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
features = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
min_version = 0.20

[author]
  name = "Brad Carruthers"
  homepage = "https://github.com/bcallumcarr"

[[original]]
  name = "Cactus"
  homepage = "https://themes.gohugo.io/cactus/"
  repo = "https://github.com/digitalcraftsman/hugo-cactus-theme"
