---
title: "About"
output: html_document
---

Hi there!

My name is Brad Carruthers and I'm currently a Master's student at the London School of Economics and Political Science. [Here](/img/carruthers-cv-18-01-2019.pdf) is my cv, [here](https://www.linkedin.com/in/brad-carruthers-7b737190/) is my LinkedIn profile and you might also want to have a look at what I've been doing on [GitHub](https://github.com/BCallumCarr).

I started this blog in January 2019, so it most likely is still a little barren. My plan is to populate it with things that I'm currently doing and that I'm interested in. Speaking of things I'm interested in: I enjoy surfing, teaching, public speaking and exploring solutions to (particularly education) problems around the world.

I have experience as an investment analyst, an Economics lecturer ([Stellenbosch University](http://www.sun.ac.za/english) in South Africa) and a Mathematics teaching assistant (also Stellenbosch University). Recently, I've worked as both an Academic Manager and Data Science teaching assistant at [iXperience](http://ixperience.co.za), an innovative EdTech company based in Cape Town, South Africa.

I am passionate about helping solve challenges in developing countries and globally - inequality, chronic poverty, [online privacy](https://www.privacy.io), and the implications of the [fourth industrial revolution](https://www.weforum.org/agenda/2016/01/the-fourth-industrial-revolution-what-it-means-and-how-to-respond) are currently at the top of my list.

Feel free to pop a mail to my school address: [b{dot}c{dot}carruthers{at}lse{dot}ac{dot}uk](mailto:b.c.carruthers@lse.ac.uk)